import mlptrain
import numpy as np
import autode as ade
from scipy.spatial.distance import cdist
import ase.io
import autode as ade
from autode.atoms import Atom, Atoms
from autode.mol_graphs import make_graph
from pathlib import Path
from typing import Optional, List, Any

from autode.log import logger


def _is_xyz_filename(value: str) -> bool:
    return isinstance(value, str) and (value.endswith(".xyz")
                                       or value.endswith(".extxyz"))


class Molecule(ade.Molecule):

    def __init__(
        self,
        arg: str = "molecule",
        smiles: Optional[str] = None,
        atoms: Optional[List["Atom"]] = None,
        solvent_name: Optional[str] = None,
        charge: Optional[int] = None,
        mult: Optional[int] = None,
        **kwargs,
    ):
        """
        A molecular species constructable from SMILES or a set of atoms,
        has default charge and spin multiplicity.

        -----------------------------------------------------------------------
        Arguments:
            arg: Name of the molecule or a .xyz filename

            smiles: Standard SMILES string. e.g. generated by Chemdraw

            atoms: List of atoms in the species

            solvent_name: Solvent that the molecule is immersed in

            charge: Charge on the molecule. If unspecified defaults to, if
                    present, that defined in a xyz file or 0

            mult: Spin multiplicity on the molecule. If unspecified defaults to, if
                  present, that defined in a xyz file or 1

        Keyword Arguments:
            name: Name of the molecule. Overrides arg if arg is not a .xyz
                  filename
        """
        logger.info(f"Generating a Molecule object for {arg}")
        super().__init__(
            name=arg if "name" not in kwargs else kwargs["name"],
            atoms=atoms,
            charge=charge if charge is not None else 0,
            mult=mult if mult is not None else 1,
            solvent_name=solvent_name,
        )
        self.smiles = smiles
        self.rdkit_mol_obj = None
        self.rdkit_conf_gen_is_fine = True

        if _is_xyz_filename(arg):
            self._init_xyz_file(
                xyz_filename=arg,
                charge=charge,
                mult=mult,
                solvent_name=solvent_name,
            )

        if smiles is not None:
            assert not _is_xyz_filename(arg), "Can't be both SMILES and file"
            self._init_smiles(smiles, charge=charge)

        # If the name is unassigned use a more interpretable chemical formula
        if self.name == "molecule" and self.atoms is not None:
            self.name = self.formula

    def _init_xyz_file(self, xyz_filename: str, **override_attrs: Any):
        """
        Initialise a molecule from a .xyz or .extxyz file using ASE.
        Overrides ade.Molecule._init_xyz_file without modifying autode directly.
        """
        # Read the file using ASE
        ase_atoms = ase.io.read(xyz_filename)

        # Convert ASE Atoms -> autode Atoms
        # Explicitly cast x, y, z to float() to avoid numpy array wrapping issues
        self.atoms = Atoms([
            Atom(atomic_symbol=sym, x=float(x), y=float(y),
                 z=float(z)) for sym, (x, y, z) in zip(
                     ase_atoms.get_chemical_symbols(), ase_atoms.positions)
        ])

        # ExtXYZ metadata stored in atoms.info
        info = ase_atoms.info

        # Extract attributes with priority to override_attrs
        if override_attrs.get("charge") is not None:
            self.charge = int(override_attrs["charge"])
        elif "charge" in info:
            self.charge = int(info["charge"])

        if override_attrs.get("mult") is not None:
            self.mult = int(override_attrs["mult"])
        elif "mult" in info:
            self.mult = int(info["mult"])
        elif "spin" in info:
            self.mult = int(info["spin"])

        if override_attrs.get("solvent_name") is not None:
            self.solvent_name = override_attrs["solvent_name"]
        elif "solvent" in info:
            self.solvent_name = str(info["solvent"])

        # Parity check for electrons vs charge/spin multiplicity
        if (sum(atom.atomic_number for atom in self.atoms) % 2 != 0
                and self.charge % 2 == 0 and self.mult == 1):
            raise ValueError(
                "Initialised a molecule from an xyz/extxyz file with "
                "an odd number of electrons but had an even "
                "charge and 2S + 1 = 1. Impossible!")

        # Set default name from file stem
        if self.name == "molecule" or self.name.endswith((".xyz", ".extxyz")):
            self.name = Path(xyz_filename).stem

        make_graph(self)
        return None

    @property
    def centroid(self) -> np.ndarray:
        """
        Centroid of this molecule

        -----------------------------------------------------------------------
        Returns:
            (np.ndarray): shape = (3,)
        """
        assert self.coordinates is not None
        return np.average(self.coordinates, axis=0)

    def is_in_box(self, box: 'mlptrain.box.Box') -> bool:
        """Is this molecule totally inside a box with an origin at
        (0,0,0) and top right corner (a, b, c) = box.size

        -----------------------------------------------------------------------
        Arguments:
            box:

        Returns:
            (bool):
        """
        assert self.coordinates is not None

        if np.min(self.coordinates) < 0.0:
            return False

        # Maximum x, y, z component of all atoms should be < a, b, c
        if max(np.max(self.coordinates, axis=0) - box.size) > 0:
            return False

        return True

    def min_distance_to(self, coords: np.ndarray) -> float:
        """Calculate the minimum distance from this molecule to a set
        of coordinates

        -----------------------------------------------------------------------
        Arguments:
            coords: shape = (n, 3)

        Returns:
            (float): Minimum distance (Å)
        """
        # Infinite distance to the other set if there are no coordinates
        if len(coords) == 0:
            return np.inf

        return np.min(
            cdist(
                coords,
                self.coordinates,  # ty: ignore[invalid-argument-type]
            )
        )

    def random_normal_jiggle(self, sigma: float = 0.01) -> None:
        """
        Add a random displacement to each atoms position.

        -----------------------------------------------------------------------
        Arguments:
            sigma: Standard deviation of the standard deviation
        """
        assert self.coordinates is not None

        dx = np.random.normal(
            scale=sigma,  # Å
            loc=0.0,
            size=(self.n_atoms, 3),
        )

        self.coordinates += dx

        return None
